### ISSUE TITLE
MCMC to generate samples under the Cauchy prior using Jeffrey's Zellner-Siow Cauchy  prior 

### ISSUE THREAD

**Issue by KenneySnell** [StatsWithR/statsr#13]
Version .1 of the StatsR package has options for call function bayes_inference(y=tthm,data = tapwater,
                statistic = "mean",
                mu_0 = 35, rscale = 1,
                prior = "JZS",
                type = "ci", method = "sim")

with the above parameters.  

Using the latest version the following parameters are not available 
a) mu_0 = 35
b)  prior = "JZS", 
c) rscale = 1, and 
d) method = "sim"

When I call the updated version of Statsr (2.1), I get approximately the same answer, but the following outputs if saved in an output variable (MCMC) are missing

a) mu
b) samples (mu,  sig2,    delta,            g)

Can you explain what happened to the Jeffrey's Zellner-Siow Cauchy and how to get this called in the latest version of Stats?

Thank you,

Kenney

**Comment by jaekookang** [comment]
I had the same problem as "unused arguments" using the bayes_inference function when following examples in chapter 5 of An Introduction to Bayesian Thinking book.

**Comment by KenneySnell** [comment]
Jaffrey

You have to go back to a previous version of R to get the function to work. 

Regards

Kenney

**Comment by merliseclyde** [comment]
fixed in version 0.3.0 (see issue #15 ). will be on CRAN shortly
