### ISSUE TITLE
bayes_inference function

### ISSUE THREAD

**Issue by jaekookang** [StatsWithR/statsr#15]
Hi, I'm trying to run `bayes_inference` function under "4.1.5 Example: TTHM in Tapwater", but encountered an error. It seems that the type of arguments changed in the newer version of `statsr` package. Could you tell me how to change arguments from the previous instruction?

```R
# This is the description in the book, which does not work.
bayes_inference(tthm, data=tapwater, prior="NG",
                mu_0 = m_0, n_0=n_0, s_0 = sqrt(s2_0), v_0 = v_0,
                stat="mean", type="ci", method="theoretical", 
                show_res=TRUE, show_summ=TRUE, show_plot=FALSE)
```

**Comment by merliseclyde** [comment]
the version used in the book was in the bayesfactor branch-  this has now been merged with the master branch and an updated version has been submitted to CRAN

**Comment by jaekookang** [comment]
Thank you for the update. I really appreciate it.
