### ISSUE TITLE
Package not avalilable for R 4.2.2

### ISSUE THREAD

**Issue by yybalam** [StatsWithR/statsr#18]
Hello.

I'm using Ubuntu 22.04, I have installed R 4.2.2 and I'm following the Week 3 from the Course 1.
Trying to install the Package I got this error:

    package ‘StatsWithR/statsr’ is not available for this version of R

Is there another way for install the package, or will be supportes this version of R?

**Comment by mine-cetinkaya-rundel** [comment]
Could you let us know how you were installing it, i.e. the code you ran to install?

**Comment by yybalam** [comment]
Finally I achieve to install from this repository. I figure that I had to install some dependencies that are not listed:

- libxml2-dev
- libssl-dev
- libcurl4-openssl-dev
- libclang-dev
- dirmngr
- gfortran

That allowed me to install the `devtools` package.
However, the `StatsWithR/statsr`cannot be installed following the instruction shown at the course (`install.packages('StatsWithR/statsr')`) but was possible following the direction listed at the README of this repo.
Nontheless, there no cue at the cours that a functional way is avaliable at this repo.

But now I'm ready following the lectures.

Thanks.
